### ISSUE TITLE
isMobile mode is not working

### ISSUE THREAD

**Issue by LaserPhaser** [grafana/xk6-browser#113]
When you use:
```
    const context = browser.newContext({

        isMobile: true
    });
```

Chrome still launch default web mode.

**Comment by imiric** [comment]
Hi, thanks for reporting this.

You're right, `isMobile` doesn't work by itself, and you'll need to set `viewport` as well.

So this works correctly:

```js
const context = browser.newContext({
  isMobile: true,
  viewport: {width: 400}
});
```

**Comment by imiric** [comment]
I took a closer look at this, and this is not an issue of `isMobile` not working, but the fact that many web sites are responsive and their UI only changes depending on the viewport size. Which is why the "workaround" of specifying a width worked.

You can see that on current `main` (990a95c) we do send the correct `mobile` argument in the CDP `Emulation.setDeviceMetricsOverride` command:

```
time="2022-04-05T12:44:02+02:00" level=trace msg="-> {\"id\":8,\"sessionId\":\"F7A4136670010AF25A08F34B6E0FD3EA\",\"method\":\"Emulation.setDeviceMetricsOverride\",\"params\":{\"width\":1280,\"height\":720,\"deviceScaleFactor\":1,\"mobile\":true,\"screenWidth\":1280,\"screenHeight\":720,\"screenOrientation\":{\"type\":\"landscapePrimary\",\"angle\":90}}}" category="cdp:send" elapsed="0 ms" goroutine=55
```

That said, doing this would be user friendlier if we exposed the already preconfigured device settings, which were previously commented out. PR #289 does this. See [this example](https://github.com/grafana/xk6-browser/blob/fc35a51eadae3ada58a9da3a97f2a4e395bccb94/examples/device_emulation.js) for how to use it.

I'll close this as it's not an issue.
