### ISSUE TITLE
Keep log output concise

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#304]
**Note:** I suggested [an approach](https://github.com/grafana/xk6-browser/discussions/157) earlier.

We've been receiving complaints from our users that the extension's log output is somewhat noisy. Excessive log output makes users worry about something wrong with their scripts, even if their scripts are totally fine.

I find our current user-facing error messages unnecessarily verbose and noisy. It would be much better if we could display separate error messages and debug logs. For example, we show the following error to the users:

`panic: unable to selectOption: element handle cannot evaluate: cannot call function on expression ("\n\t\t(node, injected, selector, strict, state, timeout, ...args) => {\n\t\t\treturn injected.waitForSelector(selector, node, strict, state, 'raf', timeout, ...args);\n\t\t}\n\t\n//# sourceURL=__xk6_browser_evaluation_script__\n") in execution context (3) in frame (39730BFD4B4E60220EF0B0A7816E7905) with session (BF9F73D22785325E395258F9B99CC591): exception "Uncaught (in promise)" (0:0): error:strictmodeviolation`

We might do the following instead:

`panic: selectOption: selector "divs" cannot select multiple elements while the strict mode is on.`

While the other details can go to the debug output.

Note: The error message I'm suggesting is just an example. The strict mode is not an implementation detail according to Playwright and we offer the strict option to the users as well. Our mileage may vary. We can discuss and decide to omit it from the user-facing error message.

**Related:**
* We received a lot of these complaints on our Slack channels.
* https://community.k6.io/t/is-there-a-way-to-suppress-warnings-in-the-console/3636/2
* https://community.k6.io/t/erro-0006-unexpected-eof-error-during-run-of-example-script/3136/4
* https://github.com/grafana/xk6-browser/issues/232 (somewhat related)
* https://github.com/grafana/xk6-browser/issues/250 (somewhat related)
* https://github.com/grafana/xk6-browser/pull/396#discussion_r896676441
* https://github.com/grafana/xk6-browser/pull/286#discussion_r866890577

**Comment by imiric** [comment]
There are some improvements to this that we previously discussed:

- Cleaning up the log messages themselves to make them less noisy by, e.g.:
  * removing the [JS expression from errors returned from `ExecutionContext.eval()`](https://github.com/grafana/xk6-browser/blob/241e40269e050624be21f94b80aca2cfed630d70/common/execution_context.go#L220-L245). This usually logs our internal wrapper functions, or in some cases, like `waitForSelector()` failures, [the entire `injected_script.js`](https://k6io.slack.com/archives/C02LAJA6EJ1/p1651568248623849?thread_ts=1651568124.618959&cid=C02LAJA6EJ1). :facepalm: In any case, this is hardly useful.
  * removing repetition, so instead of logging an error with `failed parsing options: error parsing goto options: invalid lifecycle event: "..."; must be one of: "..."`, logging `navigate frame: goto options: lifecycle ".." must be one of: "..."` would be more concise. See [this internal discussion](https://loadimpact.slack.com/archives/C033REJN4MR/p1651850058994359).

- Coming up with a way to specify log levels, or disable logs altogether per component, class name, event type, or something else...? (URL?). Our current [`XK6_BROWSER_LOG` environment variable](https://community.k6.io/t/is-there-a-way-to-suppress-warnings-in-the-console/3636/2) was added more as an internal developer option, but it's clear that users would need something more flexible. Regex would probably be too slow for this, so we'll need to think of a better approach.

**Comment by inancgumus** [comment]
> * it's clear that users would need something more flexible. Regex would probably be too slow for this, so we'll need to think of a better approach.

I suggested an approach earlier. Please see https://github.com/grafana/xk6-browser/discussions/157.

**Comment by DaveM-Performance** [comment]
When running performance tests, best practice dictates that logging during a test should be minimal ie. ERROR or at worst case WARN.  When devving the scripts picking the level is much better, so DEBUG/INFO would be acceptable.

This would be a really good addition as it would cut down on the resources used during test execution.  Always a good thing :)

**Comment by inancgumus** [comment]
Related: https://github.com/grafana/xk6-browser/pull/396#discussion_r896676441
Related: https://github.com/grafana/xk6-browser/pull/286#discussion_r866890577

Summary:

I find our messages unnecessarily verbose and noisy. The error and debug logs are different things. For example, in the real world, here is an example:

`panic: unable to selectOption: element handle cannot evaluate: cannot call function on expression ("\n\t\t(node, injected, selector, strict, state, timeout, ...args) => {\n\t\t\treturn injected.waitForSelector(selector, node, strict, state, 'raf', timeout, ...args);\n\t\t}\n\t\n//# sourceURL=__xk6_browser_evaluation_script__\n") in execution context (3) in frame (39730BFD4B4E60220EF0B0A7816E7905) with session (BF9F73D22785325E395258F9B99CC591): exception "Uncaught (in promise)" (0:0): error:strictmodeviolation`

Instead of:

`panic: selectOption: element handle evaluate: cannot call function "waitForSelector": strict mode violation`

Or, better, since user-friendly error messages are better:

`panic: selectOption: query "divs" cannot select multiple elements while strict mode is on.`

While the other details can go to the debug output.

**Comment by imiric** [comment]
I decided to split this issue into two, following [my comment above](https://github.com/grafana/xk6-browser/issues/304#issuecomment-1120940802).

Let's address cleaning up our current log messages, standardizing the syntax and making them concise in this issue (point 1). And I'll open a new issue about controling the log level per component (point 2).

**Comment by imiric** [comment]
Furthermore, while working on point 1, I think we should first reach a consensus on how our log messages are structured, so that we don't introduce this issue again.

To that end, I propose the following conventions.

Log message structure: `<process description>: <error reason>`

Examples:

- `waitForSelector "h5" in frame with URL "https://...": timed out after 100ms`
- `parsing waitForSelector options: invalid timeout value "somevalue"`
- `frame navigation to "https://test.k6.io/my_messages.php": timed out after 100ms`
- `request GET http://test.k6.io/ was interrupted: hostname test.k6.io is in a blocked pattern "*.k6.io"`


Note:

- Both the process description and the error reason should be as concise as possible, while still being sufficiently informative and actionable by the user. **Don't sacrifice descriptiveness for conciseness.** I.e. prefer longer messages that are descriptive and informative over shorter and terse ones.
  E.g. include frame URLs where possible, the time spent waiting in case of a timeout, etc.

- Don't mention phrases like "error", "cannot", "unable to", etc. The type of event is obvious from the log level (i.e. error, warning, etc.), and "cannot"/"unable to" sounds like it's a matter of not being allowed to, or not having the ability to, perform an action. This is not the case in most cases, and we can leave these words out to shorten the message.

- Don't mention internal implementation details or APIs the user doesn't care about. This will only cause confusion. E.g. `ExecutionContext.eval` is a frequently used internal method we don't need to mention at all. The user doesn't care that we evaluate JS on the browser.

  So instead of having:
  `waitForSelector "h5": evaluating JS expression in frame with URL "https://...": timed out after 0s`
  prefer:
  `waitForSelector "h5" in frame with URL "https://...": timed out after 0s`

- The process description should either contain the JS method name that was called, OR in cases when the process is internal and no public JS method is relevant, a process description using simple prose **in present continuous tense when possible**.

  E.g. `Page.goto` is the public JS method, but the actual implementation in done in the internal `FrameManager.NavigateFrame`. So the messages logged in `NavigateFrame` should be in the form of:
  `frame navigation to "https://...": timed out after 0s`
  or
  `parsing frame navigation options: invalid timeout value "somevalue"`

- Try to avoid chaining error messages. This is fine for Go errors consumed internally, but when used for logging it often exposes internal implementation details and would be confusing for users.

  Like in the example above, instead of:
  `waitForSelector "h5": evaluating JS expression in frame with URL "https://...": timed out after 0s`
  "squash" the chaining to use a single colon:
  `waitForSelector "h5" in frame with URL "https://...": timed out after 0s`

- The error reason should be user friendly and also not expose internal details.

  E.g. the current `Cannot find context with specified id (-32000)` we often see doesn't tell users anything meaningful, and it exposes internal CDP details. Instead we should translate errors like that into something user friendlier, even if it turns out to be an xk6-browser bug that they can't do anything about.
  So instead of:
  `waitForSelector "h5" in frame with URL "https://...": Cannot find context with specified id (-32000)`
  it would be better to log:
  `waitForSelector "h5" in frame with URL "https://...": execution context not found`

Let me know what you think, and I'll propose a PR following what we agree on sometime next week.

**Comment by ankur22** [comment]
A lot of what was said in the above comment (https://github.com/grafana/xk6-browser/issues/304#issuecomment-1165579869) I agree with. Some points that I'd like to make though which I think will help achieve some of the points raised above:

1. Can we use structured logging whereby the details of the error are part of the overall printed log object but not part of the message itself? E.g. `waitForSelector "h5" in frame with URL "https://...": timed out after 0s` would be `{"message":"waitForSelect in frame", "selector": "h5", "url": "https://...", "err": "timed out after 0s"}` as a structured log line. This enables us to do some interesting things with logs, i.e. we can now observe the frequency of such messages, as well as the "meta" data without having to work with the regex to do the same thing. I feel that this is important since these logs can end up in loki/datadog etc which work really well with structured logs. This will also make logging a tiny bit faster since we're not having to perform string formatting -- this isn't a very strong argument though as we're not concerned with performance at the moment.
2. In terms of extensions (e.g. `xk6-browser`) it feels like the application "works" in a similar way to a backend web service:
    1. Public API called from JS
    2. Goja translates the call
    3. Goja calls the Go exported method
    4. Go exported method calls internal methods/functions (which would further internal logical layers, just as a webservice would have)
    Now, let's say deep within one of these internal logic layers an error occurs:
    1. These errors should be easily distinguishable (if needed) by using `errors.Is` or `errors.As`;
    2. This enables us to easily identify the error down stream;
    3. This would also enable us to transform one error type into another, which would avoid chaining AND would avoid leaking the internals of the application;
    5. Finally at the last Go exported method which is sent to koja, we would do two things:
        1. Log the error, at this point, since we're able to distinguish between different error types, we wouldn't need to log the error directly if didn't need (there will be instances where this will be required), but instead an easier to understand error that's actually useful to the end user can be logged;
        2. We can `panic`/return a new `error` once again without leaking the internals.

**Comment by imiric** [comment]
@ankur22 We discussed structured logging in the past, and we certainly don't use that capability of `logrus` enough.

That said, I think there are a few issues with adopting it for our use case:

1. Structured logs are meant to facilitate machine reading (e.g. for aggregation), and not necessarily for human consumption. Especially if we dump them out as JSON, they're really not user friendly.

2. Most of our error messages are followed by a stack trace (when passed to `k6ext.Panic()`). Seeing a stack trace after a structured log line doesn't make sense visually nor conceptually. If anything, we should have a `"stack_trace"` field as part of the structured log line, with `\n` and all.

3. Since we dump the web app console logs to stdout, we have no control over the structure of these messages, so not all log lines would be structured, which kind of defeats the purpose if we're going to have a mix of outputs.

4. In theory, structured logs would be useful if we'd allow the user to decide the log format they want. k6 provides a `--console-output` flag to `run`, which allows redirecting logging to a file, but this only works for `console.{log,error,etc.}` calls in the script, and not for our internal nor site logs.
  Alternatively, we might consider outputting JSON logs if not running in a TTY, as k6 currently does that check for a similar functionality, but that's hacky IMO, and preferably we should give the user explicit control over this. An env var might work, but with all the drawbacks mentioned above, it would still be messy and likely a lot of work, so we should make sure there is enough user demand for this before tackling it.

Still, if you and @inancgumus think this is something we should consider, please open an issue specifically for structured logging and let's discuss it further.

<hr>

I agree with your second point. In general we should keep logging from internal components at a minimum, and return wrapped errors we can unwrap and translate in higher-level layers (close to JS), where we actually do the logging. In some cases we can't avoid not logging internally, but even then, we should stick to the conventions mentioned above.

**Comment by inancgumus** [comment]
I mostly agree with what you say since I have also suggested some of them. I'd prefer saying 'action' instead of 'process' as everything in xk6-browser happens around actions. And including the action in the error message is better so that users can diagnose the problems.

Log message structure: <action>: <description>: <error reason>

Is there a reason to say frame? Isn't navigation always about a frame?

```diff
- waitForSelector "h5" in frame with URL "https://...": timed out after 100ms
+waitForSelector("h5") in "https://": timed out after 100ms 
```

Both descriptive, concise, and actionable:

```diff
- parsing waitForSelector "h5" options: invalid timeout value "somevalue"
+ waitForSelector("h5"): invalid timeout value "somevalue" 
```

How would users know which action caused the problem? If they could know the action, they could fix the problem.

```diff
- frame navigation to "https://...": timed out after 100ms
+ click("selector"): navigation to "https://...": timed out after 100ms
```

Both descriptive, concise, and actionable:

```diff
- request GET http://test.k6.io/ was interrupted: hostname test.k6.io is in a blocked pattern "*.k6.io"
- click("selector"): GET "http://test.k6.io/": "test.k6.io" is in a blocked pattern "*.k6.io"
```

I'm not saying that we should do it this way. Just, my two cents.

**Comment by ankur22** [comment]
@imiric thanks for your comments on my suggestions around structured logging -- I agree that we should put this aside as it's currently not a good fit for our needs and potentially not what the customer needs, and would require a lot of work to get all logs to log out in a structured format.
