### ISSUE TITLE
Allocate browser: parse websocket url: file already closed

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#363]
It seems we have a brand new bug:

"panic: cannot allocate browser: cannot parse websocket url: scanner err: read |0: file already closed [recovered]"

IDK whether we can fix this problem as it seems to happen when we can't launch a browser. It might be possible that Github has a glitch.

---

[From the log](https://github.com/grafana/xk6-browser/runs/6705682654?check_suite_focus=true):

```
=== RUN   TestPageInputSpecialCharacters
--- FAIL: TestPageInputSpecialCharacters (0.09s)
panic: cannot allocate browser: cannot parse websocket url: scanner err: read |0: file already closed [recovered]

goroutine 14162 [running]:
...
github.com/grafana/xk6-browser/chromium.(*BrowserType).Launch(0xc0001efdc0, 0x1d2f[698](https://github.com/grafana/xk6-browser/runs/6705682654?check_suite_focus=true#step:8:699), 0xc0007e0a50, 0x0, 0x0)
	/home/runner/work/xk6-browser/xk6-browser/chromium/browser_type.go:143 +0xc4e
github.com/grafana/xk6-browser/tests.newTestBrowser(0x1d30918, 0xc000b07080, 0x0, 0x0, 0x0, 0xf)
	/home/runner/work/xk6-browser/xk6-browser/tests/test_browser.go:127 +0x66f
github.com/grafana/xk6-browser/tests.TestPageInputSpecialCharacters(0xc000b07080)
	/home/runner/work/xk6-browser/xk6-browser/tests/page_test.go:324 +0x73
testing.tRunner(0xc000b07080, 0x1b72b48)
...
```

**Comment by imiric** [comment]
This issue can be reproduced on Linux by running a test in headed mode (`headless: false`), while no display server is available.

In that case, [the error returned from `scanner.Err()`](https://github.com/grafana/xk6-browser/blob/16df8d3c504d3ad9a0fd45cf55cedbf447a22eac/common/browser_process.go#L212) will be `os.ErrClosed`, indicating that the stdout file descriptor was closed.

This is not the only reason this could happen, and the only way to determine the underlying cause is to inspect the process' stderr.

For the no display server scenario, stderr contains:

```
[6497:6497:1013/103521.932979:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[6497:6497:1013/103521.933051:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
[1013/103521.947824:ERROR:nacl_helper_linux.cc(315)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
```

This likely isn't the same cause for this error in CI, since our tests always run in headless mode, so there's probably another reason why Chromium crashed right away. I would instinctively blame the GitHub Actions environment for that, given their unreliable track record, as I don't see how this could be some internal race condition we're not handling properly. In any case, this is a _very_ rare issue in CI I haven't seen in the last few months, which again suggests that GitHub might've done some improvements on their side to minimize these types of failures (or we improved our test suite? :man_shrugging:).

So while there's likely nothing we can do about the failure itself, we can at least make the error message more informative, so that we can understand the reason if it happens again.

I did some minor changes, and on Linux we now log:

```
ERRO[0000] launching browser: getting DevTools URL: Missing X server or $DISPLAY
```

Which is just taking the first error from stderr.

Unless someone has a better suggestion, I'll polish this up a bit and create a PR early next week.
