### ISSUE TITLE
Add SetInputFiles support

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#384]
Inspired by #355, and for further PW compatibility, we might want to add `SetInputFiles` support to `Page` and `Frame`.

**Comment by justmeben** [comment]
would be much appreciated

**Comment by ankur22** [comment]
We have had to scale back how this feature works in k6 as compared to Playwright. In Playwright you have the ability to read from the local filesystem by providing the file path in the API call:

```js
await page.setInputFiles('input[id="upload"]', 'test.txt')
```

This isn't possible in the browser module for k6 since it's not safe when k6 is deployed in a remote server. This would give the browser module access to the local FS of the server. Instead you can work with the [experimental fs module](https://grafana.com/docs/k6/latest/javascript-api/k6-experimental/fs/) to provide the same functionality, albeit with a bit more boiler plate code:

```js
...
let file;
(async function () {
  file = await open('/abs/path/to/file.txt');
})();

...

export default async function () {
...
  const buffer = await readAll(file);
  page.setInputFiles('input[id="upload"]', { name: 'file.txt', mimetype: 'text/plain', buffer: encoding.b64encode(buffer) })
...
}

async function readAll(file) {
...
}
```

You can find more details and a working test script in https://github.com/grafana/xk6-browser/pull/1244.
