### ISSUE TITLE
Wrong metric sample timestamp pushed to Cloud

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#533]
On current `main` (cf033cb), running the following script:

<details>
  <summary>script.js</summary>

```javascript
import { check } from 'k6';
import { chromium } from 'k6/x/browser';

export const options = {
  vus: 1,
  duration: '60s',
}

export default function () {
  const browser = chromium.launch({
    headless: true,
  });
  const context = browser.newContext();
  const page = context.newPage();

  // Goto front page, find login link and click it
  page.goto('https://test.k6.io/', { waitUntil: 'networkidle' });
  Promise.all([
    page.waitForNavigation(),
    page.locator('a[href="/my_messages.php"]').click(),
  ]).then(() => {
    // Enter login credentials and login
    page.locator('input[name="login"]').type('admin');
    page.locator('input[name="password"]').type('123');
    // We expect the form submission to trigger a navigation, so to prevent a
    // race condition, setup a waiter concurrently while waiting for the click
    // to resolve.
    return Promise.all([
      page.waitForNavigation(),
      page.locator('input[type="submit"]').click(),
    ]);
  }).then(() => {
    check(page, {
      'header': page.locator('h2').textContent() == 'Welcome, admin!',
    });
  }).finally(() => {
    page.close();
    browser.close();
  });
}
```

</details>

... and sending the metrics to the Cloud with:

```
xk6-browser run --output cloud script.js
```

Results in the test run ending with a `Timed out` status, not showing any metric results (the metrics do appear while the test is running, but disappear when it finishes):

![2022-09-14-154703_1556x909_scrot](https://user-images.githubusercontent.com/1009277/190171633-cf8b940a-fabc-43ba-a2ff-a4143c6426f0.png)

And a strange "Started" timestamp that is ~11 days in the past in this example:

![2022-09-14-144430_551x313_scrot](https://user-images.githubusercontent.com/1009277/190171206-3c02b54a-d6ee-432e-bf10-9aa22ada192f.png)

See test run 140998 on staging for details.

After further troubleshooting it seems that _some_ metric samples are being sent with this wrong timestamp, which confuses the backend. I added some debug print statements to `k6.output.cloud.MetricsClient.PushMetric()`:

<details>
  <summary>patch</summary>

```diff
diff --git a/output/cloud/metrics_client.go b/output/cloud/metrics_client.go
index 6aef2076a..4faa66c4b 100644
--- a/output/cloud/metrics_client.go
+++ b/output/cloud/metrics_client.go
@@ -48,6 +48,18 @@ func (mc *MetricsClient) PushMetric(referenceID string, s []*Sample) error {
 	start := time.Now()
 	url := fmt.Sprintf("%s/v1/metrics/%s", mc.host, referenceID)
 
+	for _, sample := range s {
+		var ts int64
+		switch d := sample.Data.(type) {
+		case *SampleDataSingle:
+			ts = d.Time
+		case *SampleDataMap:
+			ts = d.Time
+		}
+		fmt.Printf("pushing %q sample to cloud with timestamp %s\n",
+			sample.Metric, time.Unix(0, int64(ts*1000)))
+
+	}
 	jsonStart := time.Now()
 	b, err := easyjson.Marshal(samples(s))
 	if err != nil {
```

</details>

Which shows some of the wrong timestamps:

```
pushing "vus" sample to cloud with timestamp 2022-09-14 15:14:47.180698 +0200 CEST
pushing "vus_max" sample to cloud with timestamp 2022-09-14 15:14:47.180698 +0200 CEST
pushing "data_sent" sample to cloud with timestamp 2022-09-03 06:10:11.780496 +0200 CEST
pushing "http_reqs" sample to cloud with timestamp 2022-09-03 06:10:11.899911 +0200 CEST
pushing "http_req_duration" sample to cloud with timestamp 2022-09-03 06:10:11.899911 +0200 CEST
pushing "data_received" sample to cloud with timestamp 2022-09-03 06:10:11.899911 +0200 CEST
pushing "http_req_connecting" sample to cloud with timestamp 2022-09-03 06:10:11.899911 +0200 CEST
pushing "http_req_tls_handshaking" sample to cloud with timestamp 2022-09-03 06:10:11.899911 +0200 CEST
pushing "http_req_sending" sample to cloud with timestamp 2022-09-03 06:10:11.899911 +0200 CEST
pushing "http_req_receiving" sample to cloud with timestamp 2022-09-03 06:10:11.899911 +0200 CEST
pushing "data_sent" sample to cloud with timestamp 2022-09-03 06:10:11.780496 +0200 CEST
pushing "data_sent" sample to cloud with timestamp 2022-09-03 06:10:11.899911 +0200 CEST
pushing "browser_first_meaningful_paint" sample to cloud with timestamp 2022-09-14 15:14:47.493954 +0200 CEST
pushing "browser_loaded" sample to cloud with timestamp 2022-09-14 15:14:47.512931 +0200 CEST
```

Notice that `vus` and `vus_max` are correct, but `http_req*` ones have a timestamp in the past.

This is likely some wrong int conversion for these metric emissions.

**Comment by mdcruz** [comment]
<img width="1088" alt="Screenshot 2022-09-14 at 17 58 03" src="https://user-images.githubusercontent.com/10811379/190216568-ae526a5e-80c8-474b-9582-aa8e89cc2161.png">

For more information that might be useful, when I ran a test locally and pushed the output to the cloud, you can see that the timestamp is also wrong in this view.

**Comment by inancgumus** [comment]
I can reproduce the issue locally. There are problems with `NetworkManager` request/response metric emissions. By using the test script @mdcruz shared, I see the request/response metrics are four days behind on my machine.

```log
onResponseReceived == 2022-09-16 19:56:13.236125 +0300 +03
response.timestamp   =2022-09-16 19:56:13.236125 +0300 +03
emitResponseMetrics   2022-09-16 19:56:13.236125 +0300 +03
emitResponseMetrics 2 2022-09-16 19:56:13.236125 +0300 +03

handleRequestRedirect == 2022-09-16 19:56:15.219125 +0300 +03
   response.timestamp   =2022-09-16 19:56:15.219125 +0300 +03
   emitResponseMetrics   2022-09-16 19:56:15.219125 +0300 +03
   emitResponseMetrics 2 2022-09-16 19:56:15.219125 +0300 +03

onResponseReceived == 2022-09-16 19:56:15.359375 +0300 +03
response.timestamp   =2022-09-16 19:56:15.359375 +0300 +03
emitResponseMetrics   2022-09-16 19:56:15.359375 +0300 +03
emitResponseMetrics 2 2022-09-16 19:56:15.359375 +0300 +03
```

Then, I checked the `https://test.k6.io/my_messages.php` server raw output, and it responded with the correct date (2022-09-20). So the problem is not there.

```log
curl -v https://test.k6.io/my_messages.php
...
< HTTP/1.1 200 OK
< Date: Tue, 20 Sep 2022 08:28:57 GMT
...
```

**Why are CDP request/response timestamps not correct?**

The cdp package (and the cdp protocol) uses monotonic time when calculating timestamps. And the cdp package does so by getting it from the local machine's last **boot time**. That's why there are time skews. Since the cdp package uses monotonic time in timestamp fields, we need to adjust the timestamp with the monotonic difference.

```
// walltime returns the machine's current time
off := event.walltime - event.timestamp
event.timestamp += off
```

With this change, the timestamps become accurate. However, there is not much difference between calculating the offset using the above method and simply getting it from the wall time. The only difference is that the wall time is not monotonic. So it's sensitive to machine clock changes.

I'll continue working on this tomorrow.

**Comment by ankur22** [comment]
> @imiric @ankur22 What do you think about calculating the offset vs. simply using the walltime field?

Either of them are as good as each other since both solutions use the `walltime` and so are both affected by any machine clock changes AFAICT.

Maybe the delta solution is "better". When using `walltime` to calculate the delta, would it be calculated once (i assume at the start of the test) and it then reused throughout the test?

**Comment by inancgumus** [comment]
@ankur22 That's why we're calculating the offset using the monotonic time to adjust the timestamp for machine clock changes. Since `walltime` and `timestamp` are _per-request_, they are consistent in itself.

> When using walltime to calculate the delta, would it be calculated once (i assume at the start of the test) and it then reused throughout the test?

The walltime offset calculation is done per request, so it will be specific to a request (and its response). That's how it will prevent time skews.

How frequently a local machine on cloud will change? I guess it will be super infrequent. So we can simply use the `walltime` field (without calculating the offset), and I think it will be enough for 99% of cases.

**Comment by imiric** [comment]
Nice work digging into this @inanc :clap: I wasn't aware CDP events had both a walltime and monotonic timestamp.

> What do you think about calculating the offset vs. simply using the walltime field?

I'm confused by the need to calculate using the offset to arrive at the correct time. Is there a benefit of doing that vs. just using the `walltime` field directly?

It seems to me like you'd always get the same result. I.e.:

```
c = a - b
b += c
b == a
```

So we might just use `event.walltime` without doing this, AFAICS needless, calculation.

From what I understand, monotonic time is useful for calculating intervals between samples with greater precision. So if we need to calculate the elapsed time between two events, we should use the monotonic timestamp. Because the metric samples we send to the backend require a Unix timestamp, we have no choice but to use the wall time, which depends on the system clock. I'm not sure about all the ways the backend takes this into account, but what was messing things up here is that the timestamps were inconsistent within a single test run. So as long as that's fixed, we should be fine with using `event.walltime` directly.

**Comment by inancgumus** [comment]
Thanks, Ivan 😄 

> I'm confused by the need to calculate using the offset to arrive at the correct time. Is there a benefit of doing that vs. just using the walltime field directly?

We will calculate `offset` once in [`NetworkManager.onRequest`](https://github.com/grafana/xk6-browser/blob/87a27bdfc77dbbfa278562ec92547d66e2fd089b/common/network_manager.go#L438), and then we'll add it to `resp.timestamp` in [`emitResponseMetrics`](https://github.com/grafana/xk6-browser/blob/87a27bdfc77dbbfa278562ec92547d66e2fd089b/common/network_manager.go#L213). So `event.timestamp` in [the above calculation](https://github.com/grafana/xk6-browser/issues/533#issuecomment-1252462431) is not response's timestamp.

```
off := onRequestEvent.walltime - onRequestEvent.timestamp
// later in the request/response chain
response.timestamp += off
```

> ...monotonic time is useful for calculating intervals between samples with greater precision. 

Monotonic is for preventing time-skew when measuring elapsed time. And, `timestamp` fields in `Request`/`Response` are monotonic (measure since the boot time of the machine). Only the `Request.Walltime` is not monotonic.

> k6 run --output cloud doesn't use a Cloud instance like k6 cloud does. It runs the test on your local machine, and uses the cloud output to send the metrics to the Cloud.

That's a good point. So if we directly use `walltime`, time skew can happen. Go also uses [monotonic time](https://pkg.go.dev/time#hdr-Monotonic_Clocks), and time is accurately calculated even a time skew happens. That means we can create a `Time` value `onRequest`, and then add `offset` to it. Anyway, this would probably be unnecessary since we can also add `offset` to `timestamp` fields.

I'll look more into this and come up with a solution. Thanks for your input 🙇

**Comment by inancgumus** [comment]
I ran some tests on staging, and the test ID of the last one is 141146. The results look promising.
