### ISSUE TITLE
xk6-browser not sending headers for ws requests

### ISSUE THREAD

**Issue by ns-anag** [grafana/xk6-browser#554]
Hi, I have a code :

const browser = chromium.launch({
    args: ['proxy-server=127.0.0.1:8080'],
    headless: false,
    slowMo: '500ms',
    devtools: true,  
  });
  const randomInt = String(getRandomInt());
  const context = browser.newContext({ 
    'x-ns-ext-tenant-id': 'test00' + randomInt,
    'x-authenticated-user': randomInt + '@perf.com',
})
  const page = context.newPage();
  const startTime = new Date().getTime();
  try {
    page.goto('http://webtest.local:8080/src/nx/Ball.html');
} } catch (error) {
    console.log(`Error: ${error}`);
    CounterErrors.add(1);
  }

when the page is requested, it makes a websocket request which fails:
`
ERRO[0003] WebSocket connection to 'ws://webtest.local:8080/chnws/' failed: Error during WebSocket handshake: Unexpected response code: 400  browser_source=network line_number=137 source=browser stacktrace="&{ [0xc000dbbd80 0xc000dbbdc0 0xc000dbbe00 0xc000dbbe40 0xc000dbbe80 0xc000dbbec0] <nil> <nil>}" url="blob:http://webtest.local:8080/1d58dde1-5520-429c-9d42-191830c06db3"
`
Is because it's expecting same headers for this request too, but when it's unable to find it.
What is needed to add these headers to internal websocket upgrade requests?

**Comment by ankur22** [comment]
hi @ns-anag,

Thanks for this issue. I've taken a look at this, and firstly I want to make sure that I've understood your test scenario:

1. You're setting custom headers on all requests from xk6-browser;
2. your test is requesting a html page (and you want this request to contain the custom headers);
3. this html page opens a new WS connection from a JS script (and you want the headers to be forwarded);
4. On the WS server it's expecting the custom headers before upgrading the connection?

Secondly, it looks like the headers in the `newContext` aren't being set correctly. Try using the `extraHTTPHeaders` option, like this:

```javascript
  const context = browser.newContext({
    extraHTTPHeaders: {
      'x-ns-ext-tenant-id': 'test00' + randomInt,
      'x-authenticated-user': randomInt + '@perf.com',
    },
  })
```

Hopefully this will resolve the issue you're having.

I want to point out that in my tests, I found that I couldn't set or forward custom headers when using `new WebSocket` in my javascript client code. Currently, xk6-browser cannot intercept outgoing requests and mutate them, such as adding custom headers. So, for now you will need to find a way to set headers outside of xk6-browser; you must already be doing this somehow in your app code, since we can't do them from the javascript client code?

Thanks,
Ankur

**Comment by ns-anag** [comment]
Hi @ankur22 . Thanks for the reply. Yes, you understood the scenario perfectly well.
1.  I tried using `extraHTTPHeaders={}` also but same results, the ws request still does not contain the headers we added.
2. As a work-around I am using mitmproxy to intercept requests from xk6-browser and add the necessary headers.

**Comment by imiric** [comment]
Hi @ns-anag,

like Ankur mentioned, it's currently not possible to intercept requests, but this feature is on our roadmap. The API would resemble how [Puppeteer and Playwright currently do this](https://dev.to/checkly/request-interception-with-puppeteer-and-playwright-1503). You can follow #10 to be notified when `route()` is implemented.

But we're curious how your production app adds these headers, since it's not possible to add them via the WebSocket JS API. You must have some API gateway that does this, in which case, it might make more sense to run tests against that endpoint instead of hitting the WS service directly.

**Comment by ns-anag** [comment]
Yes @imiric. We have a proxy that sets these headers for us, these headers do not come from client app. But in automated test I wanted to avoid using a proxy. But I guess it's fine now with mitmproxy.` https://github.com/grafana/xk6-browser/issues/10 can help too.`
Thank you both.

**Comment by imiric** [comment]
I see, great. We'll close this for now, but let us know if you run into any other issues.
