### ISSUE TITLE
Running a combination of high VUs on a browser-level and protocol-level caused a deadlock issue

### ISSUE THREAD

**Issue by mdcruz** [grafana/xk6-browser#600]
### Brief summary

Running a combination of high VUs on a browser-level and protocol-level caused a deadlock issue and the browser test seemed to stopped executing after 2 mins.
<img width="1239" alt="Screenshot 2022-10-24 at 11 45 53" src="https://user-images.githubusercontent.com/10811379/197508995-f68c846b-bcfb-472f-b0b6-4cff17128b31.png">

### xk6-browser version

xk6-browser pre-v0.6.0

### OS

macOS 12.6

### Chrome version

105.0.5195.125

### Steps to reproduce the problem

Run the following script on k6 cloud Staging environment

Script used: 

```
import { chromium } from 'k6/x/browser';
import { check, sleep } from 'k6';
import http from 'k6/http';

export const options = {
 scenarios: {
   browser: {
     executor: 'per-vu-iterations',
     exec: 'browser',
     vus: 100,
     maxDuration: '5m',
     iterations: '10'
   },
   news: {
     executor: 'constant-vus',
     exec: 'news',
     vus: 1000,
     duration: '10m',
   },
 },
};

export function browser() {
 const browser = chromium.launch();
 const page = browser.newPage();

 page
   .goto('https://test.k6.io/browser.php', { waitUntil: 'networkidle' })
   .then(() => {

     sleep(1);
     page.locator('#checkbox1').check();

     check(page, {
       'checkbox is checked': (p) =>
         p.locator('#checkbox-info-display').textContent() === 'Thanks for checking the box',
     });
   })
   .finally(() => {
     page.close();
     browser.close();
   });
}

export function news() {
 const res = http.get('https://test.k6.io/news.php');

 sleep(1);

 check(res, {
   'status is 200': (r) => r.status === 200,
 });
}
```

### Expected behaviour

Both tests should run successfully and metrics are sent to k6 Cloud

### Actual behaviour

The browser test seemed to stop executing after 2 mins and there were no errors in the console log, apart from a high CPU usage reported from k6 cloud.

```
    /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: cloud
     script: examples/k6-combo.test.js
     output: https://app.k6.io/runs/141586

  scenarios: (100.00%) 2 scenarios, 1100 max VUs, 10m30s max duration (incl. graceful stop):
           * browser: 10 iterations for each of 100 VUs (maxDuration: 5m0s, exec: browser, gracefulStop: 30s)
           * news: 1000 looping VUs for 10m0s (exec: news, gracefulStop: 30s)

WARN[0605] error reading a log message from the cloud, trying to establish a fresh connection with the logs service...  error="websocket: close 1000 (normal)"
     test status: Finished

Run    [======================================] Finished
```

**Comment by imiric** [comment]
This is related to https://github.com/grafana/xk6-browser/issues/601#issuecomment-1288894280, and I suggest closing this issue as well.

I'm surprised it even ran for 2 minutes :sweat_smile:

**Comment by ankur22** [comment]
I ran this same test, but altered the VU count to the following, and it still "deadlocked"/crashed.

```
export const options = {
 scenarios: {
   browser: {
     executor: 'per-vu-iterations',
     exec: 'browser',
     vus: 25,
     maxDuration: '5m',
     iterations: '10'
   },
   news: {
     executor: 'constant-vus',
     exec: 'news',
     vus: 250,
     duration: '10m',
   },
 },
};
```

**Comment by ankur22** [comment]
Oh wait! I just realised that it will run max 10*25 so 250 iterations, and that's how many browser tests it ran before stopping the browser tests. So it worked as expected? I ran 10*100 so 1000 iterations (i.e. the original test that Marie wrote) and it ran 1000 iterations and then stopped. So it must be working? I've attached a screenshot of the 1000 iteration browser test. It seems to have automatically created 4 different load executor VMs, is that correct?

<img width="1288" alt="Screenshot 2022-10-24 at 12 40 41" src="https://user-images.githubusercontent.com/1112428/197517889-87059492-34f3-478a-a028-445faa78eacf.png">

**Comment by mdcruz** [comment]
> export const options = {
>  scenarios: {
>    browser: {
>      executor: 'per-vu-iterations',
>      exec: 'browser',
>      vus: 100,
>      maxDuration: '5m',
>      iterations: '10'
>    },
>    news: {
>      executor: 'constant-vus',
>      exec: 'news',
>      vus: 1000,
>      duration: '10m',
>    },
>  },
> };

I think I have misinterpreted the results as well @ankur22. Looking at the data below, it did execute 1000 iterations (10 per VU) so it didn't cause any deadlock issues. The empty data on the rest of the timings was a bit confusing 🙃
<img width="550" alt="Screenshot 2022-10-24 at 16 06 47" src="https://user-images.githubusercontent.com/10811379/197560134-8eb560be-01a8-44c4-b03c-3a1bb6d1c69f.png">

**Comment by imiric** [comment]
This issue is slightly different from #601 and #602, since it's also running regular k6 VUs. Depending on how the k6 organization is configured, it might split the test into several instances by default, in which case the test might pass.

IIRC this split is done equally across scenarios, so that in the original case it would run 250 (regular k6) VUs for the `news` scenario, and 25 (browser) VUs for the `browser` scenario. That might still be overloading the `m5.large` instance, as 25 browser VUs alone would be difficult to run without issues, and the 250 k6 VUs are also competing for the same resources, which is why it's able to run for a little while, but crashes after a few minutes.

@mdcruz An interesting test might be to increase the number of k6 VUs to e.g. 1500, while keeping 100 browser VUs. That should make the split use 6 instances: 1500+100=1600 total VUs. At the default 300 VUs per instance, it would allocate 250 k6 VUs and ~17 browser VUs per instance, which might be runnable.

In any case, this is an issue we'll need to address eventually, as the backend must be able to know how many regular and browser VUs a test plans to allocate. Currently it has no concept of browser VUs. We still haven't started to spec out this feature, since it's not crucial for the initial beta, but we'll need to work on it soon after that.
