### ISSUE TITLE
Running 100 browser VUs seemed to have crash our backend instance

### ISSUE THREAD

**Issue by mdcruz** [grafana/xk6-browser#601]
### Brief summary

While running 100 browsers VUs using the per-vu-iterations executor, this crashed our AWS instance, which caused the test to be terminated.

### xk6-browser version

xk6-browser pre-v0.6.0

### OS

macOS 12.6

### Chrome version

105.0.5195.125

### Steps to reproduce the problem

Run the following script in k6 cloud staging:

```
import { check, sleep } from 'k6';
import { chromium } from 'k6/x/browser';

export const options = {
 scenarios: {
   messages: {
     executor: 'per-vu-iterations',
     vus: 100,
     maxDuration: '5m',
     iterations: '10'
   }
 }
};

export default function () {
 const browser = chromium.launch();
 const page = browser.newPage();

 page.goto('https://test.k6.io/my_messages.php', { waitUntil: 'networkidle' }).then(() => {
   sleep(1);
   // Enter login credentials and login
   page.locator('input[name="login"]').type('admin');
   page.locator('input[name="password"]').type('123');

   sleep(1);

   // Wait for asynchronous operations to complete
   return Promise.all([
     page.waitForNavigation(),
     page.locator('input[type="submit"]').click(),
   ]).then(() => {
     check(page, {
       'header': page.locator('h2').textContent() == 'Welcome, admin!',
     });
   }).finally(() => {
     page.close();
     browser.close();
   });
 });
}
```

### Expected behaviour

Test should run and metrics are reported to k6 cloud

### Actual behaviour

Test was aborted because the k6 process in instance #0 (amazon:us:columbus) was unexpectedly terminated. This also triggered an alert in #k6-alert-k6-sentry.

<img width="1280" alt="Screenshot 2022-10-24 at 11 53 52" src="https://user-images.githubusercontent.com/10811379/197510386-8aa67981-8e57-4939-970c-0e49045a2892.png">

**Comment by imiric** [comment]
Hi Marie,

running 100 browser VUs on a single instance is simply too resource demanding, which is why this particular test crashed. It was a `t5.large` EC2 instance, which has 2 vCPUs and 8GB RAM, so it's unreasonable to demand such a large test from it.

I see that CPU usage was at 100% for the duration of the test (all ~25s of it), and RAM usage quickly increased to ~80% before the instance stopped responding.

[I ran some performance tests a few months ago in #292](https://github.com/grafana/xk6-browser/issues/292#issuecomment-1146104095), and ran into this limitation at around ~30VUs per instance (`t3.large` in that case).

So I suggest two things in this case:

- We can configure a larger instance to be created for your tests, e.g. `m5.2xlarge` (8 vCPUs, 32GB RAM) which might be able to handle 100 browser VUs.

- Or, preferably, you can run a distributed test with 100 VUs, allocating 20 VUs per `t5.large` instance, which should be possible. I know that @sniku ran a 10hr / 100VU test recently without issues (test run 1525114 on production), though still ran into the CPU usage warning.

  Here's the configuration he used:

  ```javascript
  export let options = {
    vus: 100,
    duration: '10h',
    ext: {
      loadimpact: {
        distribution: {
          'amazon:us:columbus': { loadZone: 'amazon:us:columbus', percent: 20 },
          'amazon:it:milan': { loadZone: 'amazon:it:milan', percent: 20 },
          'amazon:bh:bahrain': { loadZone: 'amazon:bh:bahrain', percent: 20 },
          'amazon:jp:osaka': { loadZone: 'amazon:jp:osaka', percent: 20 },
          'amazon:gb:london': { loadZone: 'amazon:gb:london', percent: 20 },
        },
      },
    },
  }
  ```

So I vote for closing this issue as there's not much we can do in the codebase as far as optimizing this goes (not that there are no optimizations to be done, but nothing that would make a large impact in this case), and there's a valid workaround of running a distributed test instead.

Once we open the beta up for customers, we'll need to set some expectations about resource usage and maybe expose more resource usage information for them to troubleshoot these issues directly. But the high CPU and memory usage warnings shouldn't be ignored.

**Comment by mdcruz** [comment]
> Hi Marie,
> 
> running 100 browser VUs on a single instance is simply too resource demanding, which is why this particular test crashed. It was a `t5.large` EC2 instance, which has 2 vCPUs and 8GB RAM, so it's unreasonable to demand such a large test from it.
> 
> I see that CPU usage was at 100% for the duration of the test (all ~25s of it), and RAM usage quickly increased to ~80% before the instance stopped responding.
> 
> [I ran some performance tests a few months ago in #292](https://github.com/grafana/xk6-browser/issues/292#issuecomment-1146104095), and ran into this limitation at around ~30VUs per instance (`t3.large` in that case).
> 
> So I suggest two things in this case:
> 
> * We can configure a larger instance to be created for your tests, e.g. `m5.2xlarge` (8 vCPUs, 32GB RAM) which might be able to handle 100 browser VUs.
> * Or, preferably, you can run a distributed test with 100 VUs, allocating 20 VUs per `t5.large` instance, which should be possible. I know that @sniku ran a 10hr / 100VU test recently without issues (test run 1525114 on production), though still ran into the CPU usage warning.
>   Here's the configuration he used:
>   ```js
>   export let options = {
>     vus: 100,
>     duration: '10h',
>     ext: {
>       loadimpact: {
>         distribution: {
>           'amazon:us:columbus': { loadZone: 'amazon:us:columbus', percent: 20 },
>           'amazon:it:milan': { loadZone: 'amazon:it:milan', percent: 20 },
>           'amazon:bh:bahrain': { loadZone: 'amazon:bh:bahrain', percent: 20 },
>           'amazon:jp:osaka': { loadZone: 'amazon:jp:osaka', percent: 20 },
>           'amazon:gb:london': { loadZone: 'amazon:gb:london', percent: 20 },
>         },
>       },
>     },
>   }
>   ```
> 
> So I vote for closing this issue as there's not much we can do in the codebase as far as optimizing this goes (not that there are no optimizations to be done, but nothing that would make a large impact in this case), and there's a valid workaround of running a distributed test instead.
> 
> Once we open the beta up for customers, we'll need to set some expectations about resource usage and maybe expose more resource usage information for them to troubleshoot these issues directly. But the high CPU and memory usage warnings shouldn't be ignored.

Thanks for clarifying @imiric!

I can confirm that running it distributed fixed the issue and there are also no errors reported on the console log. Closing this issue.
<img width="1320" alt="Screenshot 2022-10-24 at 15 49 17" src="https://user-images.githubusercontent.com/10811379/197555809-f4cdec1b-7d04-4ce5-bca8-4c0cff99188f.png">
