### ISSUE TITLE
Auto-run CI tasks when k6-core updates

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#701]
Auto-running our CI tasks when k6 makes an update will allow us to detect the breaking changes as soon as possible. We might also think about doing this daily instead of per push by the k6-core.

**Comment by ka3de** [comment]
For this task, the `e2e` and `test` GH actions are a must to run daily. But I wonder if we should also run the `build` GH action in order to have some sort of daily build with specific versioning? For example by detecting if the trigger is a release or a daily run. Or maybe for the daily run we should limit it to the build section and avoid the packaging and release tasks.

**Comment by inancgumus** [comment]
I think it's fine as it is 🙂 Let's try this one (w/o the build part) and see. Then we can add the build step as well if needed.
