### ISSUE TITLE
 Generate TypeScript Type declarations for `BrowserType` API

### ISSUE THREAD

**Issue by ka3de** [grafana/xk6-browser#795]
Individual task to generate type declarations for the `BrowserType` API.
See current k6 type declarations in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/k6) repository.

Related: https://github.com/grafana/xk6-browser/issues/791

**Comment by Lipsa16QE** [comment]
waiting for this eagerly

**Comment by ankur22** [comment]
@Lipsa16QE take a look at the most recent type definitions in https://github.com/DefinitelyTyped/DefinitelyTyped/. Most of the objects are now defined. There are a couple missing (`browser` and `browserContext`), which will be updated in an upcoming release.

We will not be updating `browserType` since we're unexporting it the next release (more news to follow in the next release notes).
