### ISSUE TITLE
Work with VU.State.Options to validate browser options

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#858]
Once the `browser` options are part of `scenarios`, we need to be able to validate the options and the env vars. Options should be possible to validate with the use of `VU.State.Options`. One thing to keep in mind is whether we can validate options and env vars before the test run starts so that we can error out and warn users as early as possible.

**Comment by ka3de** [comment]
Hey @imiric , one question, in relation with this issue and the work done in https://github.com/grafana/k6/commit/948587b4a30777efd221405b21c06811bf7b4ec4. Are we missing a new method definition in the `ExecutorConfig` [interface](https://github.com/grafana/k6/blob/698e894a36bebb60a9895d3abe8e94702b929a3b/lib/executors.go#L58-L91) to be able to retrieve the [newly created](https://github.com/grafana/k6/blob/698e894a36bebb60a9895d3abe8e94702b929a3b/lib/executor/base_config.go#L23-L38) `ScenarioOptions` from executors `BaseConfig` ?

**Comment by imiric** [comment]
@ka3de: You're right. A method on `ExecutorConfig` to retrieve the options would be helpful, as otherwise you'd need to type assert all possible implementations :sweat_smile:. I also ran into this when I wanted to add some tests for this field... I'll add the method later today.

Re: your second question, you should be able to get the scenario name the VU is running in in [the same way as it's done in the `k6/execution` module](https://github.com/grafana/k6/blob/698e894a36bebb60a9895d3abe8e94702b929a3b/js/modules/k6/execution/execution.go#L83-L93). Then you can get the options only for that scenario.

There should be a friendlier API for this eventually, but this will have to do for now.

**Comment by ka3de** [comment]
Great. Thank you @imiric , and thank you for the example on how to correlate the VU with the scenario :+1:
