### ISSUE TITLE
Web Vitals metrics are not consistently reported

### ISSUE THREAD

**Issue by ka3de** [grafana/xk6-browser#914]
### Brief summary

At least some Web Vitals metrics are not consistently reported on every page navigation. This usually affects particularly the metrics:
- `browser_web_vital_lcp`
- `browser_web_vital_fid`
- `browser_web_vital_cls`
and their corresponding rating metrics. See: #915.

Initial suspicion was a race condition between the call to Web Vitals event binding from the browser execution, and the page/browser closing when the test implementation just contains a single `page.goto` for example.

But even adding a `sleep` after the navigation does not seem to fix the issue.

### xk6-browser version

Commit 45b3e8b

### OS

Ubuntu 20.04.5 LTS

### Chrome version

113.0.5672.126 (Official Build) (64-bit)

### Steps to reproduce the problem

Build a custom k6 binary:
```
xk6 build --with github.com/grafana/xk6-browser@7cfb927
```
Run the following test:
```js
import { chromium } from 'k6/x/browser';

export const options = {
    scenarios: {
        ui: {
            executor: 'shared-iterations',
            options: {
                browser: {
                    type: 'chromium',
                },
            },
        },
    },
};

export default async function() {
    const browser = chromium.launch();
    const page = browser.newPage();

    try {
        await page.goto('https://test.k6.io/', { waitUntil: 'networkidle' });
    } finally {
        page.close();
    } 
}

```

### Expected behaviour

All Web Vitals metrics are reported.

### Actual behaviour

Only FCP and TTF Web Vitals metrics are reported:
![Screenshot from 2023-05-31 08-16-50](https://github.com/grafana/xk6-browser/assets/6529572/02b56bcd-42b0-4234-acad-2c5b5a600c19)

**Comment by ka3de** [comment]
Take into account that `browser_web_vital_fid` will not be reported if the user never interacts with the page.

**Comment by inancgumus** [comment]
Related knowledge source: https://github.com/GoogleChrome/web-vitals.

**Comment by inancgumus** [comment]
Updated the issue description with some minor findings. Also updated the commit that we're making tests on: 45b3e8b.

**Comment by inancgumus** [comment]
#943 aims the fix the first part of the problem. Feel free to assign yourself to this issue besides me for the next part :)🙇

**Comment by inancgumus** [comment]
As far as I can see, this is how the metric emission works:

## Largest Contentful Paint (LCP):

Emitted: LCP is typically emitted when the largest visible element in the viewport becomes visible.
Not emitted: LCP may not be emitted if the largest element does not become visible or if the page navigates before it can be captured.

## First Input Delay (FID):

Emitted: FID is emitted when the user interacts with the page for the first time, such as clicking a button or selecting an input field.
Not emitted: FID may not be emitted if there is no user interaction during the measurement period or if there are technical limitations preventing its capture.


## Cumulative Layout Shift (CLS):

Emitted: CLS is emitted when there are layout shifts that occur during the page's lifespan.
Not emitted: CLS may not be emitted if there are no layout shifts happening or if the page navigates before capturing any layout shifts.

## Total Blocking Time (TBT):

Emitted: TBT is emitted during periods of blocking main thread activity, typically caused by long tasks.
Not emitted: TBT may not be emitted if there are no long tasks occurring or if there are technical limitations in capturing them.
